title: Knowledge Graphs and Knowledge Networks
logo: assets/logos/kg-network-optimization.png
description: Knowledge Graphs and Knowledge Networks
show_downloads: false

remote_theme: pages-themes/minimal@v0.2.0
plugins:
    - jekyll-remote-theme
